tasker/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks do
    member do
      get :setAsDone
      patch :setAsDone
      get :setAsNotDone
      patch :setAsNotDone
      get :searchByTag    
    end
    collection do   
      get :search
    end
  end

  get '/user' => "tasks#index", :as => :user_root
  
  root to: "main#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

tasker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tasker/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  acts_as_taggable

end

tasker/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_person_name

  has_many :tasks

end

tasker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end

end

tasker/app/controllers/main_controller.rb
class MainController < ApplicationController

    def index
    end

end

tasker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy setAsDone setAsNotDone ] 

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks
    #@done_tasks , @undone_tasks = [], []
    
    @done_tasks = @tasks.where(isDone: true)
    @undone_tasks = @tasks.where(isDone: false)

    @undone_tasks = @undone_tasks.order(lastEditDate: :desc)
    @done_tasks = @done_tasks.order(lastEditDate: :desc)

  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  def isDone?

    
  end


  def setAsDone
    respond_to do |format|
      if @task.update(isDone: true, lastEditDate: DateTime.now)
        format.html { redirect_to tasks_path, notice: "Task was successfully set as done." }
        #format.json { render :index, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        #format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  def setAsNotDone
    respond_to do |format|
      if @task.update(isDone: false, lastEditDate: DateTime.now)
        format.html { redirect_to tasks_path, notice: "Task was successfully set as not done." }
        #format.json { render :index, status: :ok, location: @task }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        #format.json { render json: @task.errors, status: :unprocessable_entity }
        format.js 
      end
    end
  end

  def searchByTag
    @tagged_tasks = current_user.tasks.tagged_with(params[:tag])
    @tagged_tasks = @tagged_tasks.order(lastEditDate: :desc)
  end

  def search
    if params[:search].blank?  
      redirect_to(tasks_path, alert: "Empty field!")
    else  
      parameter = params[:search].downcase  
      @results = current_user.tasks.where("lower(title) LIKE ? OR lower(description) LIKE ?", "%#{parameter}%", "%#{parameter}%")
      @results_by_tags = current_user.tasks.tagged_with(parameter)
      @results = @results + @results_by_tags
      @results = @results.sort_by(&:lastEditDate).reverse
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :isDone, :tag_list).merge(lastEditDate: DateTime.now)
    end

    def doneTask_params
      params.require(:task).permit(:title, :description, :isDone, :tag_list).merge(lastEditDate: DateTime.now)
    end

end

tasker/app/helpers/application_helper.rb
module ApplicationHelper
end

tasker/app/helpers/tasks_helper.rb
module TasksHelper
    def linked_tag_list(task)
        list = task.tag_list.map do |tag_name|
            link_to(tag_name, searchByTag_task_path(task, tag: tag_name))
        end
        safe_join(list, ", ")
    end
end

tasker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/126de7b292.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render "shared/navbar" %>

    <div class="mt-8 mx-5">
      <%= yield %>
    </div>
  </body>
</html>

tasker/app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center z-0">
    <div class="relative">    
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="relative shadow-xl sm:rounded-2xl sm:overflow-hidden">
                <div class="absolute inset-0">
                    <img class="h-full w-full object-cover" src="https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=80">
                    <div class="absolute inset-0 bg-gradient-to-r from-yellow-500 to-yellow-200" style="mix-blend-mode: multiply;"></div>
                </div>
                <div class="relative px-4 py-16 sm:px-6 sm:py-24 lg:py-32 lg:px-8">
                    <h1 class="text-center text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
                        <span class="block text-white">
                            Manage your tasks
                        </span>
                        <span class="block text-yellow-200">
                            like a pro
                        </span>
                    </h1>
                    <p class="mt-6 max-w-lg mx-auto text-center text-xl text-indigo-200 sm:max-w-3xl">
                        With tasker you can manage your tasks so you will never get lost!! Add, edit and set work done with the simplicity to keep you focused on what matters the most.
                    </p>
                    <div class="mt-10 max-w-sm mx-auto sm:max-w-none sm:flex sm:justify-center">
                        <div class="space-y-4 sm:space-y-0 sm:mx-auto sm:inline-grid sm:grid-cols-2 sm:gap-5">
                            <% if !user_signed_in? %>
                                <%= link_to "Start Tasking", new_user_registration_path, class: "home_btn" %>
                                <%= link_to "Sign in", new_user_session_path, class: "home_btn_alt" %>
                            <% else %>
                                <%= link_to "Start Tasking", new_task_path, class: "home_btn" %>
                                <%= link_to "Your Tasks", tasks_path, class: "home_btn_alt" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

tasker/app/views/shared/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<div x-data="{ mobileMenuOpen : false }" class="relative bg-white">
  <div class="max-w-8xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <%= link_to "", tasks_path, class: "logo fas fa-tasks" %>
      </div>
      <% @closed = false %>
          
      <div class="flex-grow">
          
        <label for="search" class="sr-only">
            Search
        </label>
        <div class="relative">
            <div class="pointer-events-none absolute inset-y-0 left-0 pl-3 flex items-center">
            <!-- Heroicon name: solid/search -->
              <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd" />
              </svg>
            </div>
            <%= form_tag(search_tasks_path, :method => "get", class: 'navbar-form navbar-left') do %>
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "search_input" %>
            <%= button_tag "", :class => 'hidden',:name => nil%>
            <% end %>
        </div>
          
      </div>

      <div class="-mr-2 -my-2 md:hidden">
        <button @click="mobileMenuOpen = !mobileMenuOpen" class="bg-transparent rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-yellow-500" aria-expanded="false">
            <span class="sr-only">Open menu</span>
            <!-- Heroicon name: outline/menu -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
        </button>
      </div>

      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">

        <% if user_signed_in? %>
          <%= link_to "Account", edit_user_registration_path, class: "loglink" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "ml-8 logbtn" %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path, class: "loglink" %>
          <%= link_to "Sign up", new_user_registration_path, class: "ml-8 logbtn" %>
        <% end %>

      </div>
    </div>
  </div>

  <!--
    Mobile menu, show/hide based on mobile menu state.

    Entering: "duration-200 ease-out"
      From: "opacity-0 scale-95"
      To: "opacity-100 scale-100"
    Leaving: "duration-100 ease-in"
      From: "opacity-100 scale-100"
      To: "opacity-0 scale-95"
  -->



  <div id="myNav" class="top-0 z-30 inset-x-0 p-2 transition transform origin-top-right md:hidden" :class="{ 'absolute' : mobileMenuOpen , 'hidden' : !mobileMenuOpen}"  @click.away="mobileMenuOpen = false" >
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <%= link_to "", root_path, class: "logo fas fa-tasks" %>
          </div>
          <div class="-mr-2">
            <button @click="mobileMenuOpen = !mobileMenuOpen" type="button" class="bg-transparent rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-yellow-500">
              <span class="sr-only">Close menu</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
          <nav class="grid gap-y-8">
            
          </nav>
        </div>
      </div>
      <div class="py-6 px-5 space-y-6">
        
        <div>

          <% if user_signed_in? %>

            <p class="my-6 text-center text-base font-medium text-gray-500">
              <%= form_tag(search_tasks_path, :method => "get", class: 'navbar-form navbar-left') do %>
                <%= search_field_tag :search, params[:search], placeholder: "Search", class: "block w-full bg-transparent rounded-md mb-6 py-2 pl-10 pr-3 text-sm shadow-sm placeholder-gray-400 focus:outline-none focus:bg-white focus:border-gray-400 focus:shadow-xl focus:text-gray-900 focus:placeholder-gray-500 sm:text-sm" %>
                <%= button_tag "", :class => 'hidden',:name => nil%>
              <% end %>
              
            </p>
            
            <p class="mb-6 text-center text-base font-medium text-gray-500">
              <%= link_to "Account", edit_user_registration_path, class: " whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %>
            </p>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "logbtn_mobile" %>
          
          <% else %>
            
            <%= link_to "Sign up", new_user_registration_path, class: "logbtn_mobile" %>
            <p class="mt-6 text-center text-base font-medium text-gray-500">
              Existing customer?
              <%= link_to "Sign in", new_user_session_path, class: "text-indigo-600 hover:text-indigo-500" %>
            </p>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

tasker/app/views/tasks/_done_tasks.html.erb
<tr class="shadow-lg rounded-md" id="Done-task-<%= task.id %>" >

    <td>
        <div class="block px-4 pb-1.5 pt-4">
            <%= link_to task do %>
                <div class="task_table_title">
                    <%= task.title %>
                </div>
            <% end %>
            <div class="task_table_tag">
                <%= linked_tag_list task %>
            </div>
        </div>
    </td>
    
    <td><%= link_to '', setAsNotDone_task_path(task), class: "btn-undone fas fa-times", id: "setAsNotDone", remote: true %></td>
    <td><%= link_to '', edit_task_path(task), class: "far fa-edit" %></td>
    <td><%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt mr-4", id: "deleteDone", remote: true %></td>
</tr>

tasker/app/views/tasks/_form.html.erb
<div class="my-8">
  <%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form_input" %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form_input" %>
    </div>

    <div class="field">
      <%= form.label :tag_list, "Tag list (separeted by commas)" %>
      <%= form.text_field :tag_list, value: form.object.tag_list.join(", "), class: "form_input" %>
    </div>

    <div class="field">

      <% if @task.isDone == true %>
          <div class="flex justify-center items-center">
            <h1 class="text-gray-500 mr-2">This task is done </h1> <i class="text-green-400 fas fa-check"></i>
          </div>
          <div class="flex justify-center items-center">
            <%= form.label :isDone, "Keep it as done?", class:"mr-2" %>
            <%= form.check_box :isDone %>
          </div>
        <% elsif @task.isDone == false %>
          <div class="flex justify-center items-center">
            <h1 class="text-gray-500 mr-2">This task is not done yet</h1> <h1 class="text-red-400 fas fa-times"></h1>
          </div>
          <div class="flex justify-center items-center">
            <%= form.label :isDone, "Set as done?", class:"mr-2" %>
            <%= form.check_box :isDone %>
          </div>
        <% else %>
          <div class="flex justify-center items-center">
            <%= form.label :isDone, "Set as done?", class:"mr-2" %>
            <%= form.check_box :isDone %>
          </div>
        <% end %>
      <%# <%= form.label :isDone, "Set as done?" %>
      <%# <%= form.check_box :isDone > %>
    </div>

    <div class="actions">
      <%= form.submit class: "common_btn" %>
    </div>
  <% end %>
</div>

tasker/app/views/tasks/_not_done_tasks.html.erb
<tr class="shadow-lg rounded-md w-80" id="Not-done-task-<%= task.id %>" >

  <td>
    <div class="block px-4 pb-1.5 pt-4">
      <%= link_to task do %>
        <div class="task_table_title">
          <%= task.title %>
        </div>
      <% end %>
      <div class="task_table_tag">
        <%= linked_tag_list task %>
      </div>
    </div>
  </td>

  <td><%= link_to '', setAsDone_task_path(task), class: "btn-done fas fa-check", id: "setAsDone", remote: true %></td>
  <td><%= link_to '', edit_task_path(task), class: "far fa-edit" %></td>
  <td><%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt mr-4", id: "deleteNotDone", remote: true %></td>
</tr>

tasker/app/views/tasks/destroy.js.erb
if (<%= @task.isDone == true %>)
{
    $("#Done-task-<%= @task.id %>").fadeOut(250, function(){
        $(this).remove();
    });
}else {
    $("#Not-done-task-<%= @task.id %>").fadeOut(250, function(){
        $(this).remove();
    });   
}

tasker/app/views/tasks/edit.html.erb
<div class="max-w-md mx-auto">

  <h1 class="text-4xl">Editing Task</h1>

    <%= render 'form', task: @task %>

    <%= link_to 'Show', @task %> |
    <%= link_to 'Back', tasks_path %>

</div>

tasker/app/views/tasks/index.html.erb
<div class="max-w-6xl mx-auto">

  <h1 class="text-4xl text-opacity-25"> <%= current_user.first_name %>'s Tasks</h1>

  <div class="my-8">
    <p id="notice"><%= notice %></p>
    <div class="div_add_task">
      <%= link_to 'New Task', new_task_path, class: "add_task_btn" %>
    </div>

    <div class="tasks_container">

      <div class="tasks_table">

        <div class="task_title">
          <h1 class=" text-xl text-yellow-500 text-opacity-60">Tasks To Do</h1>
        </div>

        <div class="max-w-full">
          <table class="min-w-full">
            <thead>
              <tr>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody id="not_done_body">
              <% @undone_tasks.each do |task| %>
                <div>
                  <%= render "not_done_tasks", task: task %>
                </div>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>



      <div class="tasks_table">

        <div class="task_title">
          <h1 class=" text-xl text-yellow-500 text-opacity-60">Done Tasks</h1>
        </div>

        <div class="max-w-full">
          <table class="min-w-full">
            <thead>
              <tr>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody id="done_body">
              <% @done_tasks.each do |task| %>
                <div>
                  <%= render "done_tasks", task: task %>
                </div>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>

    </div>

  </div>
</div>

tasker/app/views/tasks/new.html.erb
<div class="max-w-xs mx-auto">

    <h1 class="text-4xl">New Task</h1>

    <%= render 'form', task: @task %>

    <%= link_to 'Back', tasks_path %>

</div>

tasker/app/views/tasks/search.html.erb
<div class="max-w-6xl mx-auto">

    <h1 class="text-4xl text-opacity-25"> <%= current_user.first_name %>'s Tasks</h1>
    <div class="my-8">
        <p id="notice"><%= notice %></p>
        <div class="tasks_container">
            <div class="tasks_table">
                <div class="task_title">
                    <h1 class=" text-xl text-yellow-500 text-opacity-60">Tasks from your search - <b> <%= params[:search] %> </b> </h1>
                </div>
                <div class="max-w-full">
                    <table class="min-w-full">
                        <thead>
                            <tr>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @results.each do |task| %>
                                <div>
                                    <tr class="shadow-lg rounded-md w-80">

                                        <td>
                                            <div class="block px-4 py-1.5 pt-8">
                                                <%= link_to task do %>
                                                    <div class="task_table_title">
                                                        <%= task.title %>
                                                    </div>
                                                <% end %>
                                                <div class="task_table_tag">
                                                    <%= linked_tag_list task %>
                                                </div>
                                                <div class=" mt-1 mb-1 flex justify-center items-center">
                                                    <% if task.isDone == true %>
                                                        <h1 class="text-gray-500 mr-2">This task is done </h1> <i class="text-green-400 fas fa-check"></i>
                                                    <% else %>
                                                        <h1 class="text-gray-500 mr-2">This task is not done yet</h1> <h1 class="text-red-400 fas fa-times"></h1>
                                                    <% end %>
                                                </div>
                                            </div>
                                        </td>
                                        <% if task.isDone == true %>
                                            <td><%= link_to '', setAsNotDone_task_path(task), class: "btn-undone fas fa-times" %></td>
                                        <% else %>
                                            <td><%= link_to '', setAsDone_task_path(task), class: "btn-done fas fa-check" %></td>
                                        <% end %>
                                        <td><%= link_to '', edit_task_path(task), class: "far fa-edit" %></td>
                                        <td><%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt mr-4" %></td>
                                    </tr>
                                </div>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

tasker/app/views/tasks/searchByTag.html.erb
<div class="max-w-6xl mx-auto">

    <h1 class="text-4xl text-opacity-25"> <%= current_user.first_name %>'s Tasks</h1>
    <div class="my-8">
        <p id="notice"><%= notice %></p>
        <div class="tasks_container">
            <div class="tasks_table">
                <div class="task_title">
                    <h1 class=" text-xl text-yellow-500 text-opacity-60">Tasks with the tag - <b> <%= params[:tag] %> </b> </h1>
                </div>
                <div class="max-w-full">
                    <table class="min-w-full">
                        <thead>
                            <tr>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @tagged_tasks.each do |task| %>
                                <div>
                                    <tr class="shadow-lg rounded-md w-80">

                                        <td>
                                            <div class="block px-4 py-1.5 pt-8">
                                                <%= link_to task do %>
                                                    <div class="task_table_title">
                                                        <%= task.title %>
                                                    </div>
                                                <% end %>
                                                <div class="task_table_tag">
                                                    <%= linked_tag_list task %>
                                                </div>
                                                <div class=" mt-1 mb-1 flex justify-center items-center">
                                                    <% if task.isDone == true %>
                                                        <h1 class="text-gray-500 mr-2">This task is done </h1> <i class="text-green-400 fas fa-check"></i>
                                                    <% else %>
                                                        <h1 class="text-gray-500 mr-2">This task is not done yet</h1> <h1 class="text-red-400 fas fa-times"></h1>
                                                    <% end %>
                                                </div>
                                            </div>
                                        </td>
                                        <% if task.isDone == true %>
                                            <td><%= link_to '', setAsNotDone_task_path(task), class: "btn-undone fas fa-times" %></td>
                                        <% else %>
                                            <td><%= link_to '', setAsDone_task_path(task), class: "btn-done fas fa-check" %></td>
                                        <% end %>
                                        <td><%= link_to '', edit_task_path(task), class: "far fa-edit" %></td>
                                        <td><%= link_to '', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "far fa-trash-alt mr-4" %></td>
                                    </tr>
                                </div>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

tasker/app/views/tasks/setAsDone.js.erb
$("#Not-done-task-<%= @task.id %>").fadeOut(250, function(){
    $(this).remove();
    $("#done_body").prepend('<%= j render "done_tasks", task: @task %>');
    $("#Done-task-<%= @task.id %>").hide().fadeIn(250);
});

tasker/app/views/tasks/setAsNotDone.js.erb
$("#Done-task-<%= @task.id %>").fadeOut(250, function(){
    $(this).remove();
    $("#not_done_body").prepend('<%= j render "not_done_tasks", task: @task %>');
    $("#Not-done-task-<%= @task.id %>").hide().fadeIn(250);
});

tasker/app/views/tasks/show.html.erb
<div class="max-w-xl mx-auto">

  <h1 class="text-4xl text-yellow-600 text-opacity-25">My Task</h1>

  <div class="my-8">
  
    <p id="notice"><%= notice %></p>

    <div class="my-4 flex justify-center">
      <h1 class="text-2xl"><%= @task.title %></h1>
    </div>

    <div class="justify-center">
      <h3 class="text-gray-500">Description</h3>
      <div class="show_desc">
        <%= @task.description %>
      </div>
    </div>

    <div class="justify-center">
      <h3 class="text-gray-500">Tags</h3>
      <div class="show_tags">
        <%= linked_tag_list @task %>
      </div>
    </div>

    <div class="justify-center">
      <h3 class="text-gray-500">Last Edit Date</h3>
      <div class="show_time">
        <%= @task.lastEditDate.strftime("%H:%M") %> -
        <%= @task.lastEditDate.to_date %>
      </div>
    </div>

    <div class="my-4 flex justify-center items-center">
      <% if @task.isDone == true %>
        <h1 class="text-gray-500 mr-2">This task is done </h1> <i class="text-green-400 fas fa-check"></i>
      <% else %>
        <h1 class="text-gray-500 mr-2">This task is not done yet</h1> <h1 class="text-red-400 fas fa-times"></h1>
      <% end %>
    </div>

    <div>
      <%= link_to 'Edit', (edit_task_path(@task) if user_signed_in? && current_user == @task.user), class: "common_btn" %> |
      <%= link_to 'Back', tasks_path %>
    </div>
    
  </div>
</div>